# Generated by Django 3.2.9 on 2021-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hvn',
            name='brand',
        ),
        migrations.AddField(
            model_name='hvn',
            name='brand',
            field=models.ManyToManyField(to='outlet.Campain'),
        ),
    ]
