# Generated by Django 3.2.9 on 2021-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarytable',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='salarytable',
            name='staff',
        ),
        migrations.AlterField(
            model_name='hvn',
            name='brand',
            field=models.CharField(choices=[('tigerTP', 'TigerTP'), ('tigerFA', 'TigerFA'), ('tigerHZA', 'TigerHZA'), ('strongbow', 'Strongbow Festive'), ('heineken', 'Heineken Festive'), ('bivina', 'Bivina Festive'), ('larue', 'larue Festive')], default='heineken', max_length=200),
        ),
        migrations.AlterField(
            model_name='saleperson',
            name='brand',
            field=models.CharField(choices=[('tigerTP', 'TigerTP'), ('tigerFA', 'TigerFA'), ('tigerHZA', 'TigerHZA'), ('strongbow', 'Strongbow Festive'), ('heineken', 'Heineken Festive'), ('bivina', 'Bivina Festive'), ('larue', 'larue Festive')], default='heineken', max_length=200),
        ),
        migrations.DeleteModel(
            name='BasicSalary',
        ),
        migrations.DeleteModel(
            name='SalaryTable',
        ),
    ]
