# Generated by Django 3.2.9 on 2021-12-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hvn',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hvn_vip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='saleperson',
            name='name',
        ),
    ]
