# Generated by Django 3.2.9 on 2021-12-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211202_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytable',
            name='basic_salary',
            field=models.ForeignKey(default='0', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='users.basicsalary'),
        ),
    ]
