# Generated by Django 3.2.9 on 2021-12-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_auto_20211207_0012'),
        ('users', '0002_auto_20211204_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleperson',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.campain'),
        ),
    ]
