# Generated by Django 3.2.9 on 2021-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_salarytable_basic_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hvn',
            old_name='phone',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='hvn_vip',
            old_name='phone',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='saleperson',
            old_name='phone',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='hvn',
            name='position',
        ),
        migrations.RemoveField(
            model_name='hvn_vip',
            name='position',
        ),
        migrations.AddField(
            model_name='hvn',
            name='brand',
            field=models.CharField(choices=[('tiger', 'Tiger'), ('strongbow', 'Strongbow'), ('heineken', 'Heineken'), ('bivina', 'Bivina'), ('larue', 'larue')], default='heineken', max_length=200),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_HVN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_HVNVip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_salePerson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleperson',
            name='outlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleperson',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
