# Generated by Django 3.2.9 on 2021-12-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outlet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consumerApproachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumers_approach', models.CharField(max_length=255)),
                ('consumers_brough', models.CharField(max_length=255)),
                ('Total_Consumers', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='giftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift1_received', models.IntegerField(default=0)),
                ('gift2_received', models.IntegerField(default=0)),
                ('gift3_received', models.IntegerField(default=0)),
                ('gift4_received', models.IntegerField(default=0)),
                ('gift5_received', models.IntegerField(default=0)),
                ('gift1_given', models.IntegerField(default=0)),
                ('gift2_given', models.IntegerField(default=0)),
                ('gift3_given', models.IntegerField(default=0)),
                ('gift4_given', models.IntegerField(default=0)),
                ('gift5_given', models.IntegerField(default=0)),
                ('gift1_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift2_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift3_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift4_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift5_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('outlet_address', models.CharField(max_length=255)),
                ('outlet_Name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_table', models.IntegerField(default=0)),
                ('other_beer_table', models.IntegerField(default=0)),
                ('brand_table', models.IntegerField(default=0)),
                ('HVN_table', models.IntegerField(default=0)),
                ('total_table', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo')),
            ],
        ),
        migrations.CreateModel(
            name='posmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=outlet.models.upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo')),
            ],
        ),
        migrations.CreateModel(
            name='overallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.ImageField(upload_to=outlet.models.report)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consumer_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.consumerapproachreport')),
                ('gift_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.giftreport')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo')),
                ('posm_Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.posmreport')),
                ('table_Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.tablereport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='giftreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='consumerapproachreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
    ]
