# Generated by Django 3.2.9 on 2021-12-16 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereport',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablereport',
            name='campain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.campain'),
        ),
        migrations.AddField(
            model_name='tablereport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='report_sale',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report_sale',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='posmreport',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posmreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='consumer_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.consumerapproachreport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='gift_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.giftreport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='posm_Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.posmreport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='table_Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.tablereport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outletinfo',
            name='compain',
            field=models.ManyToManyField(to='outlet.Campain'),
        ),
        migrations.AddField(
            model_name='giftreport',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='consumerapproachreport',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumerapproachreport',
            name='campain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.campain'),
        ),
        migrations.AddField(
            model_name='consumerapproachreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
    ]
