# Generated by Django 3.2.9 on 2021-12-04 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinform',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='outlet.giftinform'),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='posmReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.posminform'),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='saleReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.saleinform'),
        ),
        migrations.AddField(
            model_name='posminform',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outletinfo',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftinform',
            name='SP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
