# Generated by Django 3.2.9 on 2021-12-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posminform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleinform',
            name='user',
        ),
    ]
