# Generated by Django 3.2.9 on 2021-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
    ]
