# Generated by Django 3.2.9 on 2021-12-04 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outlet.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consumerApproachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumers_approach', models.CharField(max_length=255)),
                ('consumers_brough', models.CharField(max_length=255)),
                ('Total_Consumers', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='giftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift1_received', models.IntegerField(default=0)),
                ('gift2_received', models.IntegerField(default=0)),
                ('gift3_received', models.IntegerField(default=0)),
                ('gift4_received', models.IntegerField(default=0)),
                ('gift5_received', models.IntegerField(default=0)),
                ('gift1_given', models.IntegerField(default=0)),
                ('gift2_given', models.IntegerField(default=0)),
                ('gift3_given', models.IntegerField(default=0)),
                ('gift4_given', models.IntegerField(default=0)),
                ('gift5_given', models.IntegerField(default=0)),
                ('gift1_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift2_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift3_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift4_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('gift5_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='overallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.ImageField(upload_to=outlet.models.report)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consumer_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.consumerapproachreport')),
                ('gift_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.giftreport')),
            ],
        ),
        migrations.CreateModel(
            name='posmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=outlet.models.upload_to)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_table', models.IntegerField(default=0)),
                ('other_beer_table', models.IntegerField(default=0)),
                ('brand_table', models.IntegerField(default=0)),
                ('HVN_table', models.IntegerField(default=0)),
                ('total_table', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posminform',
            name='SP',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='SP',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='posmReport',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='saleReport',
        ),
        migrations.RemoveField(
            model_name='saleinform',
            name='SP',
        ),
        migrations.RenameField(
            model_name='outletinfo',
            old_name='date',
            new_name='created',
        ),
        migrations.DeleteModel(
            name='giftInform',
        ),
        migrations.DeleteModel(
            name='posmInform',
        ),
        migrations.DeleteModel(
            name='reportData',
        ),
        migrations.DeleteModel(
            name='saleInform',
        ),
        migrations.AddField(
            model_name='tablereport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='posmreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='posm_Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.posmreport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='table_Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.tablereport'),
        ),
        migrations.AddField(
            model_name='overallreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
        migrations.AddField(
            model_name='consumerapproachreport',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.outletinfo'),
        ),
    ]
