# Generated by Django 3.2.9 on 2021-12-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_auto_20211206_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('heineken', 'Heineken'), ('tiger', 'Tiger'), ('strongbow', 'Strongbow'), ('bivina', 'Bivina'), ('larue', 'Larue')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='outletinfo',
            name='ouletID',
            field=models.CharField(blank=True, default='00', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.brand')),
            ],
        ),
        migrations.AddField(
            model_name='outletinfo',
            name='compain',
            field=models.ManyToManyField(to='outlet.Campain'),
        ),
    ]
