# Generated by Django 3.2.9 on 2021-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_auto_20211206_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campain',
            name='brand',
        ),
        migrations.AlterField(
            model_name='campain',
            name='program',
            field=models.CharField(choices=[('tigerTP', 'TAB_TGR'), ('tigerFA', 'FES_TGR'), ('tigerHZA', 'HOT_TGR'), ('heineken', 'TAB_HNK'), ('heineken_hnk', 'SPE_HNK'), ('STB', 'FES_SBW'), ('bivina', 'TAB_BVN'), ('Larue', 'TAB_LRE')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
