# Generated by Django 3.2.9 on 2021-12-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_auto_20211207_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outletinfo',
            options={'ordering': ['id']},
        ),
    ]
