# Generated by Django 3.2.9 on 2021-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_alter_outletinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereport',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='tablereport',
            name='other_table',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
