# Generated by Django 3.2.9 on 2021-12-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_alter_posmreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereport',
            name='campain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlet.campain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campain',
            name='program',
            field=models.CharField(choices=[('tigerTP', 'TAB_TGR'), ('tigerFA', 'FES_TGR'), ('tigerHZA', 'HOT_TGR'), ('heineken', 'TAB_HNK'), ('heineken_hnk', 'SPE_HNK'), ('STB', 'FES_SBW'), ('bivina', 'TAB_BVN'), ('Larue', 'TAB_LRE'), ('Larue_SPE', 'SPE_LRE')], max_length=200),
        ),
    ]
