# Generated by Django 3.2.9 on 2021-12-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0006_auto_20211207_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereport',
            name='HVN_table',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tablereport',
            name='brand_table',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tablereport',
            name='other_beer_table',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tablereport',
            name='other_table',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tablereport',
            name='total_table',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
