# Generated by Django 3.2.9 on 2021-12-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0006_auto_20211212_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerapproachreport',
            name='campain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlet.campain'),
            preserve_default=False,
        ),
    ]
