# Generated by Django 3.2.9 on 2021-12-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlet', '0007_auto_20211207_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_brand', models.CharField(default='0', max_length=255)),
                ('beer_HVN', models.CharField(default='0', max_length=255)),
                ('beer_other', models.CharField(default='0', max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
