# Generated by Django 3.2.9 on 2021-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0007_consumerapproachreport_campain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftreport',
            name='gift1_remaining',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift2_remaining',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift3_remaining',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
