# Generated by Django 3.2.9 on 2021-12-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0008_auto_20211213_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletinfo',
            name='created_by_HVN',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
