# Generated by Django 3.2.9 on 2021-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0009_remove_consumerapproachreport_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftreport',
            name='gift4_given',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='gift4_received',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='gift4_remaining',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='gift5_given',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='gift5_received',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='gift5_remaining',
        ),
        migrations.RemoveField(
            model_name='giftreport',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift1_given',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift1_received',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift2_given',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift2_received',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift3_given',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftreport',
            name='gift3_received',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
