# Generated by Django 3.2.9 on 2021-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0010_auto_20211208_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereport',
            name='total_table',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
